# Netlify configuration for NuxtPapier

[build]
# Build command for static generation
command = "pnpm generate"

# Publish directory
publish = ".output/public"

# Headers for better caching of static assets
[[headers]]
for = "/images/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/_nuxt/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA fallback if needed
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
conditions = { Role = [ "admin" ] }

# Environment variables (if needed)
[build.environment]
NODE_VERSION = "20"
NODE_OPTIONS = "--max-old-space-size=4096"
NITRO_PRESET = "static"
