// Types for TOC functionality (still needed for the component)
export interface TocLink {
  id: string
  text: string
  depth: number
  children?: TocLink[]
}

// Utility types for content queries (not generated by Nuxt Content)
export interface ContentQuery {
  tags?: string[]
  category?: string
  status?: 'draft' | 'published' | 'archived'
  limit?: number
  skip?: number
  sort?: Record<string, 1 | -1>
}

// Note: BlogPost, BlogPostAuthor, and BlogPostImage types are now automatically
// generated by Nuxt Content from the schema defined in content.config.ts
